### PR TITLE
homework week4

### PR DESCRIPTION
**Pull request by hnnhack**
https://dazzling-lalande-11fe5b.netlify.com/week3

### CODE REVIEW

**Comment by hnnhack** [comment]
https://dazzling-lalande-11fe5b.netlify.com/week3

**Comment by hnnhack** [comment]
https://dazzling-lalande-11fe5b.netlify.com/week3

**Comment by ArcoMul** [comment]
Hi @hnnhack, good job into combining all the homework into one application. I'm currently seeing two files about homework 1 and homework 2. I guess you only use one of these files? Could you clean up your branch by deleting the file which isn't needed?

Also it would be good to split up your homework 2 and 3 files into multiple files. So that you don't have 5 components in one file. This makes a better understandable file and code structure.

Good luck!

**Comment by hnnhack** [comment]
Hi @ArcoMul, thanks for your reviewing. For your suggestions,..
1 -  I'm currently seeing two files about homework 1 and homework 2. I guess you only use one of these files? Could you clean up your branch by deleting the file which isn't needed?
 + You are right to see the 2 files Homework 1 and Homework 2. But, I am using both of them. And Both of them are needful, I can't delete it.
2 - Also it would be good to split up your homework 2 and 3 files into multiple files. So that you don't have 5 components in one file. This makes a better understandable file and code structure.
+ Both Homework 1, 2 and 3  are separate files. And with then inside the component folder NavBar.js and RouterContainer.js. They are already 5 JS files inside the components folder. Please look it again and let me know anything unclear.

Many thanks for your all kind of efforts passed 4 weeks. 
Best regards,..

**Comment by ArcoMul** [comment]
Hi @hnnhack 

There are a lot of files in this pull request which are not being used by your hw-week4/react-route application. Head over to the 'Files Changed' tab and see which you can delete. I just verified that there are 3 whole directories which you can delete.

About splitting up the files I meant that all the components of your homework 2 are in one file now. For homework 3 it doesn't make sense since you only have one component. But give it a try to split up `Week2.js` in multiple files.

Good luck!

**Comment by hnnhack** [comment]
Hi @ArcoMul !
I divide all components to the separate files which you mentioned above. And I deleted some unnecessary files inside hw-week/react-route folder. 
Thanks for your suggestions.

**Comment by ArcoMul** [comment]
I'm still seeing the files. I guess deletion and committing didn't go right. Let take a look at it after class!

**Comment by ArcoMul** [comment]
Yes, super! 👍

**Pull request closed without merging**
