### PR TITLE
Alusine -homework-weeks4

### PR DESCRIPTION
**Pull request by alquinex**

### CODE REVIEW

**Comment by alquinex** [comment]
Hi @shrynx,
Thanks for the feedback and for your time. Since we had to build the week4 homework based on the week3, I had to create week4 branch within week3. That's why you see a lot of files I guess.
I am actually having troubles now separating them.
But this is the path for the week4:
React/react-hyf/reactrouter
The week4 application and all its files sit in the 'reactrouter' folder.
I hope this will help ;)

**Comment by fedefu** [comment]
@shrynx is this assignment clear or does it need to be pushed again? Thanks!

**Comment by ArcoMul** [comment]
Hi @alquinex, I think all you have to do is to delete the folder `react-hyf-client`, since that doesn't seem to be used for the homework of week4.

Besides that would optionally be cool if `/` actually showed `/home`, a website should start at its homepage I would say :)

**Comment by alquinex** [comment]
Hi @ArcoMul,
Looks better after the deletion, thanks! I thought of a different approach ;)

Hi @shrynx,
It looks better now with the PR;)

**Comment by ArcoMul** [comment]
Super :-)

**Pull request closed without merging**
