### PR TITLE
Week 5 including week 3 and 4

### PR DESCRIPTION
**Pull request by itemah26**

### CODE REVIEW

**Comment by isaachinman** [comment]
Hi @itemah26, thanks for catching up on the homework. Before we can start to review your work, we need to be able to actually run the app.

I don't know how this was working on your machine, but it seems you haven't ejected CRA, nor taken the steps necessary to support decorators. The relevant links are in the homework brief, and were also posted in Slack.

screen shot 2018-01-26 at 15 21 03

**Comment by itemah26** [comment]
Hi Isaac
I only uploaded the src files not the whole app, maybe this is why.

**Comment by isaachinman** [comment]
We'll need everything necessary to run the app.

**Comment by itemah26** [comment]
there is now a new folder mt-todo-app with every file in there.

**Comment by isaachinman** [comment]
I now get this error:



You need to install `babel-plugin-transform-decorators-legacy` as a dependency.

**Comment by itemah26** [comment]
but it works with no problems on my machine, I did the steps of mobx decoration from the link you sent on slack.

**Comment by isaachinman** [comment]
> but it works with no problems on my machine

This is a classic developer statement!

Delete your `node_modules` directory and try to install deps and run your app, you'll see the error. Alternatively, you can clone your PR into a fresh directory and you will see it as I do.

**Comment by itemah26** [comment]
I got another err
Error: Cannot find module 'chalk'

**Comment by isaachinman** [comment]
Did you do `yarn install`?

**Comment by itemah26** [comment]
no sorry I install it now

**Comment by itemah26** [comment]
yes right, and now I should run npm install babel-plugin-transform-decorators-legacy --save to fix this?

**Comment by isaachinman** [comment]
That is correct. You probably ran that command without the `--save` flag, so that's why it worked on your machine - you had installed the dependency for yourself, but not updated your `package.json` to tell future developers they also need to install it.

**Comment by itemah26** [comment]
OK nice to know that, thanks Isaac

**Comment by itemah26** [comment]
can you see the app now, or we need to hangout and I share my screen to show you my hw?

**Comment by itemah26** [comment]
It works now after installing babel-plugin-transform-decorators-legacy

**Comment by isaachinman** [comment]
You need to commit and push the changes, then I can take a look at your project.

**Comment by isaachinman** [comment]
Thanks. I have run out of time for today, but will look at this over the weekend.

**Pull request closed without merging**
