### PR TITLE
w4mahmut

### PR DESCRIPTION
**Pull request by mahmutkaya**

### CODE REVIEW

**Comment by isaachinman** [comment]
Please stop opening PRs and closing them immediately. We all get email notifications. Only submit your work when it is ready for review.

**Comment by mahmutkaya** [comment]
I'm so sorry @isaachinman and others, I didn't know that you are getting notifications..

**Comment by isaachinman** [comment]
It's OK, is there something you need help on?

**Comment by mahmutkaya** [comment]
Thank you.. I think w4 is ok. I will start the w5 homework and hopefully finish soon.

**Pull request closed without merging**
