### PR TITLE
Week1 isaac

### PR DESCRIPTION
**Pull request by gisaac85**

### CODE REVIEW

**Comment by isaachinman** [comment]
Looks like your lint failed, there are four errors to fix.

**Comment by gisaac85** [comment]
Which kind of errors ?
Because the project is running well!!!

**Comment by gisaac85** [comment]
Ok I see it 🤙

**Comment by isaachinman** [comment]
Check the Travis log. You have four lint errors.

The procedure for HW submission is changing starting with class 14. If you want to work ahead, you will need to do some extra work/reading:

https://github.com/HackYourFuture/React/blob/master/homework-submission/HOMEWORK.md

Pay attention to the second condition in the above document.

**Pull request closed without merging**
