### PR TITLE
homework is done

### PR DESCRIPTION
**Pull request by moesi88**

### CODE REVIEW

**Comment by isaachinman** [comment]
Hey @moesi88, please try to reference the week number in your commit so we know what homework this is. Thanks!

**Comment by moesi88** [comment]
Ok bro ✌🏻

**Comment by isaachinman** [comment]
Hi @moesi88, also you've kept your data inside a directory called `week1`, but I will assume this is week 2's homework.

**Comment by isaachinman** [comment]
Actually, it looks like this _is_ last week's homework. This is a static list of todos with no state or toggling. I'm going to close this PR, please reopen a new one with week 2's homework when it's ready.

**Pull request closed without merging**
