### PR TITLE
week4

### PR DESCRIPTION
**Pull request by naghamfarwati**

### CODE REVIEW

**Comment by naghamfarwati** [comment]
Hi @isaachinman yes,, but i have to fix the button of do it toggleDone action ,,after i fix the delete button, the Done button didn’t work,, can you help me to fix it??

**Comment by isaachinman** [comment]
@naghamfarwati Your problem lies in the fact that you copy/pasted code from our in-class work to your homework.

I would suggest you start with ctrl+f in your project, searching for "isLiked".

**Comment by naghamfarwati** [comment]
@isaachinman yes, but that after i tried with my function alot... and when it didn’t work, i tried to do the same function that you did in the class,,, any way today i will send another solution to you 😊

**Comment by isaachinman** [comment]
The problem is a simple naming problem, you are calling things "done" and "isLiked" at the same time. Just sort out your naming and you'll find that it already works!

**Pull request closed without merging**
